### ISSUE TITLE
Batch Data Entry: Error from Sandbox to Production

### ISSUE THREAD

**Issue by BarbaraMorais** [SalesforceFoundation/Batch-Entry-for-Salesforce.com#37]
Hi All, 
I installed batch data entry on sandbox and now I got error on  the Change Set deployment to production related to " In field: field - no CustomField named CCI_Transition_Support__c.Batch__c found".
Someone knows the solution for it? Should I uninstall the batch data entry on sandbox and just install it on production?
Thanks!

**Comment by davidhabib** [comment]
Sounds like you are trying to deploy something that has a reference to a custom field you added to the CCI_Transition_Support object.

**Comment by davidhabib** [comment]
this is a user problem, not an issue in the package.

**Comment by BarbaraMorais** [comment]
Sorry, David, but you're right, isn't an issue from data batch entry, but an user problem. I didn't found solution for this error on my researches. Anyway, I'll check if all fields mapped on batch data entry settings was mapped on change set deployment to production. Thank you!
