### ISSUE TITLE
Batch Data Entry Settings error

### ISSUE THREAD

**Issue by jcdewitt** [SalesforceFoundation/Batch-Entry-for-Salesforce.com#38]
I receive the following error when I open the tab for Batch Data Entry Settings:
Maximum view state size limit (135KB) exceeded. Actual view state size for this page was 166.688KB

This error only occurs in our Production system, in Sandbox I can adjust the fields and settings.
Jon

**Comment by judisohn** [comment]
Hi @jcdewitt I've seen this error when the older Batch Data Entry app is in use in an org that has the latest Nonprofit Success Pack. The Batch features have been rolled in to that app and therefore we're no longer directly supporting or updating this legacy stand alone app. If you're using the latest Nonprofit Success Pack, you can use the batch entry features that are very similar to what you're used to but directly on Contact, Opportunity, Account and Lead and configured through Field Sets on those objects.
